const HomeProducts = [
  {
    id: 1,
    Name: "product1",
    Price: 76000,
    imgen: "../images/modelo1.jpg",
    cat: "women's fashion",
    type: "style",
  },
  {
    id: 2,
    Name: "product2",
    Price: 83000,
    imgen: "../images/modelo2.jpg",
    cat: "women's fashion",
    type: "new",
  },
  {
    id: 3,
    Name: "product3",
    Price: 61000,
    imgen: "../images/modelo3.jpg",
    cat: "women's fashion",
    type: "top",
  },
  {
    id: 4,
    Name: "product4",
    Price: 63000,
    imgen: "../images/modelo4.jpg",
    cat: "women's fashion",
    type: "style",
  },
  {
    id: 5,
    Name: "product5",
    Price: 92000,
    imgen: "../images/modelo5.jpg",
    cat: "women's fashion",
    type: "top",
  },
  {
    id: 6,
    Name: "product6",
    Price: 78000,
    imgen: "../images/modelo6.jpg",
    cat: "women's fashion",
    type: "new",
  },
  {
    id: 7,
    Name: "product7",
    Price: 63000,
    imgen: "../images/modelo7.jpg",
    cat: "women's fashion",
    type: "style",
  },
  {
    id: 8,
    Name: "product8",
    Price: 76000,
    imgen: "../images/modelo8.jpg",
    cat: "women's fashion",
    type: "style",
  },
  {
    id: 9,
    Name: "product9",
    Price: 89000,
    imgen: "../images/modelo9.jpg",
    cat: "women's fashion",
    type: "style",
  },
  {
    id: 10,
    Name: "product10",
    Price: 68000,
    imgen: "../images/modelo10.jpg",
    cat: "women's fashion",
    type: "top",
  },
  {
    id: 11,
    Name: "product11",
    Price: 73000,
    imgen: "../images/modelo11.jpg",
    cat: "women's fashion",
    type: "new",
  },
  {
    id: 12,
    Name: "product12",
    Price: 63000,
    imgen: "../images/modelo12.jpg",
    cat: "women's fashion",
    type: "top",
  },
  {
    id: 13,
    Name: "product13",
    Price: 66000,
    imgen: "../images/modelo13.jpg",
    cat: "women's fashion",
    type: "new",
  },
  {
    id: 14,
    Name: "product14",
    Price: 92000,
    imgen: "../images/modelo14.jpg",
    cat: "women's fashion",
    type: "style",
  },
  {
    id: 15,
    Name: "product14",
    Price: 92000,
    imgen: "../images/calzado1.jpg",
    cat: "footwear",
    type: "style",
  },
  {
    id: 15,
    Name: "product15",
    Price: 128000,
    imgen: "../images/calzado6.jpg",
    cat: "footwear",
    type: "new",
  },
  {
    id: 16,
    Name: "product16",
    Price: 142000,
    imgen: "../images/calzado7.jpg",
    cat: "footwear",
    type: "top",
  },
  {
    id: 17,
    Name: "product17",
    Price: 104000,
    imgen: "../images/calzado8.jpg",
    cat: "footwear",
    type: "style",
  },
  {
    id: 18,
    Name: "product18",
    Price: 132000,
    imgen: "../images/calzado9.jpg",
    cat: "footwear",
    type: "new",
  },
  {
    id: 19,
    Name: "product19",
    Price: 121000,
    imgen: "../images/calzado10.jpg",
    cat: "footwear",
    type: "top",
  },
  {
    id: 20,
    Name: "product20",
    Price: 114000,
    imgen: "../images/calzado1.jpg",
    cat: "footwear",
    type: "style",
  },
  {
    id: 21,
    Name: "product21",
    Price: 137000,
    imgen: "../images/calzado2.jpg",
    cat: "footwear",
    type: "new",
  },
  {
    id: 22,
    Name: "product22",
    Price: 148000,
    imgen: "../images/calzado3.jpg",
    cat: "footwear",
    type: "top",
  },
  {
    id: 23,
    Name: "product23",
    Price: 114000,
    imgen: "../images/calzado4.jpg",
    cat: "footwear",
    type: "style",
  },
  {
    id: 24,
    Name: "product24",
    Price: 108000,
    imgen: "../images/calzado5.jpg",
    cat: "footwear",
    type: "new",
  },
];

export default HomeProducts;
